cucumber/cucumber-jvm-scala

- README.md
Add sbt dependency format for easier copy and paste
> sbt dependency format

- .travis.yml
- examples/src/main/scala/cucumber/examples/scalacalculator/RpnCalculator.scala
- pom.xml
- scala/pom.xml
- scala/scala_2.13/pom.xml
- scala/sources/src/main/scala/cucumber/api/scala/ScalaDsl.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaBackend.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaHookDefinition.scala
- scala/sources/src/main/scala/cucumber/runtime/scala/ScalaSnippetGenerator.scala
Hopefully, this fixes .travis file and tests.
In this PR I've added the minimal set of code changes for a Scala 2.13 build. 
Since 2.13, the import 'scala.jdk.CollectionConverters' is preferred for Java <=> Scala collection conversion. 
However, I thought it better to leave warning, rather than change the build (having separate code directory for Scala versions) -  just for one import statement: 2.14 & 3 will use the 2.13 convention and better to just change the import statement in a future version.  If you did want separate sources, I think this would be a good first step anyway.
> scala 2.13

- CHANGELOG.md
- pom.xml
- scala/sources/src/main/groovy/I18n.scala.gsp
- scala/sources/src/main/groovy/generate-i18n-dsl.groovy
- Update Gherkin dependency for language traits generation to 9.2.0 (same as Cucumber Java).
- Update Groovy templates to use new `GherkinDialectProvider` methods
> Update Gherkin version to 9.2.0

- CHANGELOG.md
- README.md
- docs/default_jackson_datatable_transformer.md
- docs/transformers.md
- pom.xml
- scala/pom.xml
- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- scala/scala_2.13/pom.xml
- scala/sources/src/main/scala/io/cucumber/scala/JacksonDefaultDataTableEntryTransformer.scala
- scala/sources/src/test/resources/tests/jackson/Jackson.feature
- scala/sources/src/test/scala/tests/jackson/JacksonSteps.scala
- scala/sources/src/test/scala/tests/jackson/RunJacksonTest.scala
Aims to fix #31 
Users can use the `JacksonDefaultDataTableEntryTransformer` trait and benefit from automatic transformation to case classes.
- New optional trait `JacksonDefaultDataTableEntryTransformer`
- Documentation
> Add optional Jackson Default DataTable transformer

- CHANGELOG.md
- README.md
- examples/pom.xml
- pom.xml
- scala/pom.xml
- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- scala/scala_2.13/pom.xml
- scala/sources/src/main/scala/io/cucumber/scala/Scenario.scala
- Upgrade to Cucumber Core 5.7.0
- Replicate changes of Cucumber Java 5.7.0
> Upgrade to Cucumber 5.7.0

- scala/pom.xml
- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- scala/scala_2.13/pom.xml
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDefaultDataTableEntryTransformerDefinition.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDsl.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaStepDefinition.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaBackendTest.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaDslDocStringTypeTest.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaDslHooksTest.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaDslStepsTest.scala
- scala/sources/src/test/scala/tests/cukes/StepDefs.scala
- scala/sources/src/test/scala/tests/cukes/TypeRegistryConfiguration.scala
- scala/sources/src/test/scala/tests/object/ObjectSteps.scala
Fix #51 
Only applied for Scala 2.13 because it's easy to ignore some warnings with the `@nowarn` annotation and it's not that easy to do in 2.12 or 2.11 (need to use a compiler plugin but not sure how to plug it with Maven).
> Add recommended list of scalac flags for Scala 2.13

- CHANGELOG.md
- docs/datatables.md
- scala/sources/src/main/scala/io/cucumber/scala/Implicits.scala
- scala/sources/src/test/resources/tests/datatables/DatatableAsScala.feature
- scala/sources/src/test/scala/tests/datatables/DatatableAsScalaSteps.scala
AIms to fix #56 
Import the new `Implicits` object and benefit from conversions methods to Scala types on the `DataTable` type:
```scala
import io.cucumber.scala.Implicits._
Given("the following table as List of Map") { (table: DataTable) =>
val scalaTable: Seq[Map[String, Option[String]]] = table.asScalaMaps
// ...
}
```
> Add Implicits object to help datatable transformations

- Makefile
- scripts/update-install-doc.sh
- Add "task" in `Makefile` to update the `docs/install.md` file on release (same process as for the CHANGELOG)
- Add script to actually do the update using sed
> Add task and script to automatically update install doc on release

- CHANGELOG.md
- docs/hooks.md
- scala/sources/src/main/scala/io/cucumber/scala/GlueAdaptor.scala
- scala/sources/src/main/scala/io/cucumber/scala/IncorrectHookDefinitionException.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDsl.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDslRegistry.scala
- scala/sources/src/main/scala/io/cucumber/scala/Utils.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaBackendTest.scala
- scala/sources/src/test/scala/io/cucumber/scala/steps/errors/incorrectclasshooks/IncorrectClassHooksDefinition.scala
- scala/sources/src/test/scala/io/cucumber/scala/steps/errors/incorrectobjecthooks/IncorrectObjectHooksDefinition.scala
Aims to fix #60 
If an incorrect hook is defined and this cannot be caught at compile time, then an exception is raised at runtime with a message similar to this:
```
Some hooks are not defined properly:
- IncorrectClassHooksDefinition.scala:11 (BEFORE)
- IncorrectClassHooksDefinition.scala:14 (BEFORE_STEP)
- IncorrectClassHooksDefinition.scala:17 (AFTER)
- IncorrectClassHooksDefinition.scala:20 (AFTER_STEP)
This can be caused by defining hooks where the body returns a Int or String rather than Unit.
For instance, the following code:
Before {
someInitMethodReturningInt()
}
Should be replaced with:
Before {
someInitMethodReturningInt()
()
}
```
-----
This PR also include a small refactoring of the `GlueRegistry` to use immutable types with `private var` rather than mutable types with …
> Raise exceptions on incorrect hook definition

- scala/sources/gen.scala
- scala/sources/src/main/scala/io/cucumber/scala/IncorrectStepDefinitionException.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDsl.scala
- scala/sources/src/test/scala/io/cucumber/scala/ScalaDslStepsTest.scala
Related to #3 
As a first step, I suggest to improve the error message so that users don't need to dive into the stacktrace and Cucumber Scala code to understand what's going on.
The error message will look like this:
```
The arguments received doesn't match the step definition.
This can happen if you are using a regular expression in your step definition with optional capture groups but mandatory parameters.
For instance:
Given("""^I am logged in(?: as (.+))?$""") { (user: String) =>
// Some code
}
For now, the easiest solution is to declare two steps: one with the capture groups, one without.
If you feel this is not working for you, please manifest yourself on https://github.com/cucumber/cucumber-jvm-scala/issues/3
```
The error message also incentivize people to manifest themselves if …
> Improve error message in case of optional capture groups

- scala/sources/src/test/resources/tests/misc/OptionalCaptureGroups.feature
- scala/sources/src/test/scala/tests/misc/OptionalCaptureGroupsSteps.scala
- scala/sources/src/test/scala/tests/misc/RunMiscTest.scala
Relates to #3 
This PR just add a test to highlight that it's possible to use optional capture groups as Java's `Optional` and map them again to Scala's `Option`.
> Add tests to highlight mapping of optional capture groups

- scala/scala_2.11/pom.xml
- scala/scala_2.12/pom.xml
- scala/sources/src/test/scala/tests/cukes/RunCukesTest.scala
- scala/sources/src/test/scala/tests/cukes/TypeRegistryConfiguration.scala
- scala/sources/src/test/scala/tests/datatables/RunDatatablesTest.scala
- scala/sources/src/test/scala/tests/docstring/RunDocStringTest.scala
- scala/sources/src/test/scala/tests/isolated/RunIsolatedTest.scala
- scala/sources/src/test/scala/tests/jackson/RunJacksonTest.scala
- scala/sources/src/test/scala/tests/misc/RunMiscTest.scala
- scala/sources/src/test/scala/tests/object/RunObjectTest.scala
- scala/sources/src/test/scala/tests/parametertypes/RunParameterTypesTest.scala
- Remove `strict` flag on `CucumberOptions` as it's now the default since Cucumber 6.x
- Remove `TypeRegistryConfigurer` tests as it's been deprecated since 5.x
> Remove deprecated tests

- CHANGELOG.md
- docs/datatables.md
- docs/transformers.md
- scala/sources/src/main/scala/io/cucumber/scala/Implicits.scala
- scala/sources/src/test/resources/tests/datatables/DatatableAsScala.feature
- scala/sources/src/test/scala/tests/datatables/DatatableAsScalaSteps.scala
Aims to resolve #83 
Add `asScalaRawXxx` methods to transform DataTable to collections _without_ `Option`s when it's not necessary.
For instance:
```scala
DataTableType { map: Map[String, String] =>
CustomType(map("key1"), Option(map("key2")), map("key3"))
}
Given("the following table as Scala List of custom type") { (table: DataTable) =>
val data: Seq[CustomType] = table.asScalaRawList[CustomType]
// Do something..
}
```
> Add asScalaRaw extension methods to DataTable

- CHANGELOG.md
- docs/transformers.md
- scala/scala_2.11/src/main/scala/io/cucumber/scala/package.scala
- scala/sources/src/main/scala/io/cucumber/scala/DataTableDefinitionBody.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalCellDefinition.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalEntryDefinition.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalRowDefinition.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDataTableTypeDefinition.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDataTableTypeDetails.scala
- scala/sources/src/main/scala/io/cucumber/scala/ScalaDsl.scala
- scala/sources/src/test/resources/tests/datatables/DataTableType.feature
- scala/sources/src/test/scala/tests/datatables/DataTableTypeSteps.scala
Aims to resolve #84 
Add the 3 following new possible definitions:
- `DataTableType { (entry: Map[String, Option[String]]) => ... }`
- `DataTableType { (row: Seq[Option[String]]) => ... }`
- `DataTableType { (cell: Option[String]) => ... }`
> Add new DataTableType definitions with Option input values

- pom.xml
WIth `cucumber-parent:2.1.1` several plugins have been added to the dependency management section. These no longer need explicit version numbers in this project.
> Remove versions from managed plugins

- .github/workflows/build.yml
- build.sbt
- project/build.properties
- project/plugins.sbt
This MR aims to cover two things:
- define the `versionScheme` that the library follows as recommended for upcoming sbt 1.5.x
- provide feedback on MR about binary/source compatibility by using _sbt-version-polivy_ plugin
More info at https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html
> Version policy

- Makefile
- build.sbt
- gpg.sh
- project/plugins.sbt
Latest sbt-pgp release fixes the original issue and read the passphrase in `PGP_PASSPHRASE` environment variable now.
> chore: 🤖 Remove the custom gpg script

- Makefile
Necessary since Docker image uses sbt 1.5.x
> fix: 🐛 Bind ~/.cache/sbt directory in Docker release process

- Makefile
Using `root` instead of `cukebot` for all operations.
Related to https://github.com/cucumber/build/pull/62
> chore: 🤖 Fix release process for latest cucumber-build image

- .github/workflows/release-github.yml
- .github/workflows/release-mvn.yml
- .github/workflows/release-sbt.yml
- .gitignore
- Makefile
- RELEASING.md
* Added GitHub Actions workflows for automating releases
* Updated RELEASING.md guide
Automate releases! 🎉 No more need to use the big docker image! 🎉 
- :bank: Refactoring/debt (improvement to code design or tooling without changing behaviour)
> Add automated release workflows and update releasing guide

- CHANGELOG.md
- build.sbt
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaBackend.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/UnknownClassType.scala
- cucumber-scala/src/test/scala/io/cucumber/scala/ScalaBackendTest.scala
- cucumber-scala/src/test/scala/io/cucumber/scala/steps/dependencyinjection/Injected.scala
- cucumber-scala/src/test/scala/io/cucumber/scala/steps/dependencyinjection/Injector.scala
- docs/usage.md
- integration-tests/picocontainer/src/test/resources/cucumber.properties
- integration-tests/picocontainer/src/test/resources/di/di.feature
- integration-tests/picocontainer/src/test/scala/di/DI_A.scala
- integration-tests/picocontainer/src/test/scala/di/DI_B.scala
- integration-tests/picocontainer/src/test/scala/di/DI_C.scala
- integration-tests/picocontainer/src/test/scala/di/RunDependencyInjectionTest.scala
This PR fixes the way `class` vs `object` are identified by Cucumber Scala: until now, any class not having a no-arg constructor was assumed to be an `object` which is false.
With this PR, classes with no public constructor are considered to be `object` but other ones (including classes with 1-arg or 2-args.. constructors) are considered as regular classes.
This has the side-effect of **fixing integration with picocontainer and other DI modules** available with Cucumber.
_Note: the identification of wheter a type is a `class` or an `object` is still perfectible but should be good in 99% of the cases. Additional error messages have been added so that users which would be in the remaining 1% are able to have a clearer error and contact us._
Fixes #4  and #175 .
- :bug: Bug fix (non-breaking …
> Allow usage of class with args and dependency injection

- .github/workflows/build.yml
Currently the test action is configured to only run on pull requests. This means Renovate had to make https://github.com/cucumber/cucumber-jvm-scala/pull/360 to see if the change it wanted to make would pass. 
Renovate works best when it can quietly upgrade minor and patch changes when there is a passing build. This requires running the CI jobs for pushes to `renovate/**` branches.  
By enabling builds on pushes to  `renovate/**` Renovate can quietly do it's work. Additionally building any pushes to `main` will ensure that if multiple MR's cross each other when being merged, the build status for each will be known making it easier to isolate problems.
- :bank: Refactoring/debt/DX (improvement to code design, tooling, documentation etc. without changing behaviour)
> Automatically merge minor and patch upgrades

- CHANGELOG.md
- build.sbt
Since we want to support JDK 21 we need to bump Scala up to 2.12.18
PR https://github.com/cucumber/cucumber-jvm-scala/pull/365
- :boom: Scala bump 2.12.16 to 2.12.18
> Bump Scala 2.12.16 to 2.12.18 for JDK21

- .github/workflows/release-sbt.yml
With Sonatype requiring the usage of a token instead of username/password. The username can no longer be hardcoded and must also be read from secrets.
Fixes: #376
> Configure Sonatype Nexus Username

- RELEASING.md
We don't announce releases anymore.
Closes https://github.com/cucumber/cucumber-jvm-scala/issues/378
> docs(releasing): update release section

- CHANGELOG.md
- cucumber-scala/src/main/scala/io/cucumber/scala/AbstractGlueDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/DataTableTypeDsl.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/DefaultTransformerDsl.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/DocStringTypeDsl.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ParameterTypeDsl.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableCellDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableEntryDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalCellDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalEntryDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableOptionalRowDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableRowDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableTypeDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDataTableTypeDetails.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDefaultDataTableCellTransformerDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDefaultDataTableEntryTransformerDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDefaultParameterTransformerDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDefaultTransformerDetails.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDocStringTypeDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaDocStringTypeDetails.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaHookDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaParameterTypeDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaParameterTypeDetails.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/ScalaStaticHookDefinition.scala
- cucumber-scala/src/main/scala/io/cucumber/scala/Utils.scala
#404 
- :bug: Bug fix (non-breaking change which fixes a defect)
> Fix location wherever it was wrongly defined
